services:
  nodejs_mongo_docker:
    image: nodejs_mongo_docker
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/test
    ports:
      - 3000:3000
    volumes:
      - .:/code/my-app
    links:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: