services:
  mongodb:
    image: mongo
    command: mongod --quiet --logpath /dev/null 

  nodejs_mongo_docker:
    image: nodejs_mongo_docker
    build: .
    depends_on:
      - "mongodb"
    ports:
      - 3000:3000
    volumes:
      - .:/code/my-app

