services:
  nodejs_mongo_docker:
    image: nodejs_mongo_docker
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/code/my-app
    links:
      - mongodb
    command: "npm run test"

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: