services:
  nodejs_mongo_docker:
    image: nodejs_mongo_docker
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/test
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - .:/code/my-app
    networks:
      - my_net

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - my_net

networks:
  my_net:
    driver: bridge


  data: