services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - my_net
  nodejs_mongo_docker:
    image: nodejs_mongo_docker
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/code/my-app
    networks:
      - my_net



networks:
  my_net:
    driver: bridge