name: test

on:
  push:
    branches:
      - main
  pull_request:
    brances: 
      - main

jobs:
  runner-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code 
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      
      - name: Run docker-compose tests
        run: docker-compose -p tests run --rm nodejs_mongo_docker npm run test

      - name: Stop integration tests
        run: docker-compose down

      #TODO - uncomment
      - name: Start containers
        run: docker-compose up -d

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
