name: test

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code 
        uses: actions/checkout@v2
      
      - name: Run tests using Jest
        run: npm run tests