name: test

on:
  push:
    branches:
      - main

jobs:
  runner-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        volumes:
          - data:/data/db

    steps:
      - name: Checkout repo code 
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build docker container
        run: docker build -t node-docker --target test .

      - name: Run docker container with tests
        run: docker run --rm --name node-test node-docker
     
      # - name: Start docker-compose to run containers
      #   run: docker-compose build -t node-docker --target test . 
      
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down